export const FETCH = 'fetch'
export const CONFIG = 'config'
export const SHOW_INFORMATION_MESSAGE  = 'showInformationMessage'
export const FILE_CONTENT = 'fileContent'
export const ON_FILE_CONTENT = 'onFileContent'
export const HIGHLIGHT_STYLES = 'HighlightStyles'
export const GET_IMAGE = 'getImage'